models:
 "<model_name>": # model: "gpt-4-turbo"  # or gpt-3.5-turbo
   api_type: "openai"  # or azure / ollama / groq etc.
   base_url: "<your base url>" 
   api_key: "<your api key>"
   temperature: 0
 "<model_name>":  
   api_type: "openai"  
   base_url: "<your base url>"
   api_key: "<your api key>"
   temperature: 0

search:
  engines:
    google:
      api_key: "<your_serper_api_key>"  # Serper.dev API Key
  request_settings:
    timeout: 30
    max_results_per_query: 5